# Evolver Loop 4 - LB Feedback Analysis

## Submission Results
- **exp_000**: CV 70.6761 | LB 70.6761 (gap: 0.0000)
- **exp_003**: CV 70.6761 | LB 70.6761 (gap: 0.0000)

## Key Finding: Perfect CV-LB Alignment
The CV and LB scores are IDENTICAL, which means:
1. Our scoring function is correct
2. Our overlap detection is correct
3. The baseline is truly at 70.676102

## The Challenge
- Target: 68.919154
- Current: 70.676102
- Gap: 1.756948 (2.49% improvement needed)

## What We've Tried (All Failed)
1. Fractional translation - 0 improvement
2. SA + local search + fractional translation - 0 improvement
3. bbox3 optimizer (80 rounds) - 0 improvement
4. tree_packer_v21 - 0 improvement
5. Ensemble from 731 CSV files - all better scores have overlaps

## Key Insight from Research
To break below 70, we need **multi-tree lattice packings** with 3-, 4-, or 5-tree repeating units, not just optimization of existing solutions.

In [1]:
import pandas as pd
import numpy as np
from shapely.geometry import Polygon
from shapely.ops import unary_union
import matplotlib.pyplot as plt

# Tree geometry
TX = np.array([0, 0.125, 0.0625, 0.2, 0.1, 0.35, 0.075, 0.075, -0.075, -0.075, -0.35, -0.1, -0.2, -0.0625, -0.125])
TY = np.array([0.8, 0.5, 0.5, 0.25, 0.25, 0, 0, -0.2, -0.2, 0, 0, 0.25, 0.25, 0.5, 0.5])

def parse_value(val):
    if isinstance(val, str) and val.startswith('s'):
        return val[1:]
    return str(val)

def build_polygon(x, y, angle):
    angle_rad = float(angle) * np.pi / 180.0
    cos_a = np.cos(angle_rad)
    sin_a = np.sin(angle_rad)
    vertices = [(TX[i] * cos_a - TY[i] * sin_a + float(x),
                 TX[i] * sin_a + TY[i] * cos_a + float(y)) for i in range(15)]
    return Polygon(vertices)

def get_score_for_n(df, n):
    prefix = f"{n:03d}_"
    rows = df[df['id'].str.startswith(prefix)]
    if len(rows) != n:
        return float('inf')
    
    all_points = []
    for _, row in rows.iterrows():
        x = float(parse_value(row['x']))
        y = float(parse_value(row['y']))
        deg = float(parse_value(row['deg']))
        poly = build_polygon(x, y, deg)
        all_points.extend(list(poly.exterior.coords))
    
    all_points = np.array(all_points)
    side = max(all_points.max(axis=0) - all_points.min(axis=0))
    return (side ** 2) / n

print("Functions loaded")

Functions loaded


In [2]:
# Load baseline and analyze score breakdown
baseline_df = pd.read_csv('/home/code/submission_candidates/candidate_000.csv')

scores = []
for n in range(1, 201):
    score = get_score_for_n(baseline_df, n)
    scores.append({'n': n, 'score': score, 'contribution': score})

scores_df = pd.DataFrame(scores)
print(f"Total score: {scores_df['score'].sum():.6f}")
print(f"Target: 68.919154")
print(f"Gap: {scores_df['score'].sum() - 68.919154:.6f}")
print()
print("Score breakdown by N range:")
for start in [1, 11, 21, 51, 101, 151]:
    end = min(start + 9, 200) if start < 101 else min(start + 49, 200)
    range_score = scores_df[(scores_df['n'] >= start) & (scores_df['n'] <= end)]['score'].sum()
    print(f"  N={start:3d}-{end:3d}: {range_score:.4f}")

Total score: 70.676102
Target: 68.919154
Gap: 1.756948

Score breakdown by N range:
  N=  1- 10: 4.3291
  N= 11- 20: 3.7282
  N= 21- 30: 3.6889
  N= 51- 60: 3.5971
  N=101-150: 17.1441
  N=151-200: 16.8487


In [3]:
# Identify which N values have the most room for improvement
# Theoretical minimum for N trees is approximately sqrt(N) * tree_area
# But for small N, the packing efficiency is much worse

print("Top 20 N values by score contribution:")
top_n = scores_df.nlargest(20, 'score')
for _, row in top_n.iterrows():
    print(f"  N={int(row['n']):3d}: score={row['score']:.6f}")

print("\nSmall N values (1-20) contribute:", scores_df[scores_df['n'] <= 20]['score'].sum())
print("Medium N values (21-100) contribute:", scores_df[(scores_df['n'] > 20) & (scores_df['n'] <= 100)]['score'].sum())
print("Large N values (101-200) contribute:", scores_df[scores_df['n'] > 100]['score'].sum())

Top 20 N values by score contribution:
  N=  1: score=0.661250
  N=  2: score=0.450779
  N=  3: score=0.434745
  N=  5: score=0.416850
  N=  4: score=0.416545
  N=  7: score=0.399897
  N=  6: score=0.399610
  N=  9: score=0.387415
  N=  8: score=0.385407
  N= 15: score=0.379203
  N= 10: score=0.376630
  N= 21: score=0.376451
  N= 20: score=0.376057
  N= 11: score=0.375736
  N= 22: score=0.375258
  N= 16: score=0.374128
  N= 26: score=0.373997
  N= 12: score=0.372724
  N= 13: score=0.372323
  N= 25: score=0.372144

Small N values (1-20) contribute: 8.057294945777112
Medium N values (21-100) contribute: 28.62602603061413
Large N values (101-200) contribute: 33.992781421700585


In [4]:
# Calculate efficiency for each N
# Efficiency = (N * tree_area) / (bounding_box_area)
# Tree area is approximately 0.35 * 1.0 = 0.35 (rough estimate)

tree_area = 0.35  # Approximate

efficiencies = []
for n in range(1, 201):
    score = scores_df[scores_df['n'] == n]['score'].values[0]
    bbox_area = score * n  # score = side^2 / n, so side^2 = score * n
    efficiency = (n * tree_area) / bbox_area
    efficiencies.append({'n': n, 'efficiency': efficiency, 'score': score})

eff_df = pd.DataFrame(efficiencies)

print("Efficiency by N range (higher is better):")
for start in [1, 11, 21, 51, 101, 151]:
    end = min(start + 9, 200) if start < 101 else min(start + 49, 200)
    avg_eff = eff_df[(eff_df['n'] >= start) & (eff_df['n'] <= end)]['efficiency'].mean()
    print(f"  N={start:3d}-{end:3d}: avg efficiency={avg_eff:.4f}")

print("\nLowest efficiency N values (most room for improvement):")
lowest_eff = eff_df.nsmallest(10, 'efficiency')
for _, row in lowest_eff.iterrows():
    print(f"  N={int(row['n']):3d}: efficiency={row['efficiency']:.4f}, score={row['score']:.6f}")

Efficiency by N range (higher is better):
  N=  1- 10: avg efficiency=0.8283
  N= 11- 20: avg efficiency=0.9389
  N= 21- 30: avg efficiency=0.9490
  N= 51- 60: avg efficiency=0.9731
  N=101-150: avg efficiency=1.0209
  N=151-200: avg efficiency=1.0388

Lowest efficiency N values (most room for improvement):
  N=  1: efficiency=0.5293, score=0.661250
  N=  2: efficiency=0.7764, score=0.450779
  N=  3: efficiency=0.8051, score=0.434745
  N=  5: efficiency=0.8396, score=0.416850
  N=  4: efficiency=0.8402, score=0.416545
  N=  7: efficiency=0.8752, score=0.399897
  N=  6: efficiency=0.8759, score=0.399610
  N=  9: efficiency=0.9034, score=0.387415
  N=  8: efficiency=0.9081, score=0.385407
  N= 15: efficiency=0.9230, score=0.379203


In [5]:
# Key insight: To close the 1.76 point gap, we need to improve across all N values
# But small N values have the worst efficiency and contribute disproportionately

# Calculate how much improvement we need per N value
target = 68.919154
current = scores_df['score'].sum()
gap = current - target

print(f"Current total: {current:.6f}")
print(f"Target: {target:.6f}")
print(f"Gap: {gap:.6f}")
print()
print(f"Average improvement needed per N: {gap / 200:.6f}")
print(f"Percentage improvement needed: {100 * gap / current:.2f}%")
print()
print("If we could improve each N by 2.49%:")
for n in [1, 2, 5, 10, 50, 100, 200]:
    current_score = scores_df[scores_df['n'] == n]['score'].values[0]
    improved_score = current_score * 0.9751
    improvement = current_score - improved_score
    print(f"  N={n:3d}: {current_score:.6f} -> {improved_score:.6f} (save {improvement:.6f})")

Current total: 70.676102
Target: 68.919154
Gap: 1.756948

Average improvement needed per N: 0.008785
Percentage improvement needed: 2.49%

If we could improve each N by 2.49%:
  N=  1: 0.661250 -> 0.644785 (save 0.016465)
  N=  2: 0.450779 -> 0.439555 (save 0.011224)
  N=  5: 0.416850 -> 0.406470 (save 0.010380)
  N= 10: 0.376630 -> 0.367252 (save 0.009378)
  N= 50: 0.360753 -> 0.351770 (save 0.008983)
  N=100: 0.345531 -> 0.336927 (save 0.008604)
  N=200: 0.337731 -> 0.329322 (save 0.008410)


## Strategy Analysis

### What We Know:
1. The baseline is at a VERY tight local optimum - standard optimizers cannot improve it
2. The gap to target is 1.76 points (2.49% improvement needed)
3. Small N values (1-20) have the worst efficiency and contribute disproportionately
4. All CSV files with better scores have overlapping trees

### What Research Suggests:
1. **Multi-tree lattice packings** with 3-, 4-, or 5-tree repeating units can break below 70
2. **Symmetric solutions** dramatically shrink search space while covering optimal region
3. **Grid-based approaches** with SA optimization on lattice parameters
4. The "super-fast-simulated-annealing-with-translations" kernel uses grid configs

### Key Approaches to Try:
1. **Lattice-based packing for large N** - Generate grid configurations and optimize
2. **Symmetric solutions for small N** - Exhaustive search with symmetry constraints
3. **Novel repeating patterns** - 3-tree, 4-tree, 5-tree unit cells
4. **Very long random restarts** - Start from scratch with different initial configs